help() {
    echo "Commandes disponibles:"
    echo "help :            Affiche les commandes disponibles"
    echo "ls :              Liste les fichiers et dossiers (y compris les cachés)"
    echo "rm <file> :       Supprime un fichier"
    echo "rmd <directory> : Supprime un dossier"
    echo "about :           Affiche une description du programme"
    echo "version :         Affiche la version du prompt"
    echo "age :             Demande votre âge et indique si vous êtes majeur ou mineur"
    echo "quit :            Quitte le prompt"
    echo "profil :          Affiche toutes les informations sur vous-même"
    echo "passw :           Change le mot de passe avec confirmation"
    echo "cd <directory> :  Change de répertoire"
    echo "pwd :             Affiche le répertoire actuel"
    echo "hour :            Affiche l'heure actuelle"
    echo "httpget :         Télécharge le code source HTML d'une page web dans un fichier spécifié"
    echo "smtp :            Envoie un mail avec une adresse, un sujet et le corps du mail"
    echo "open <file> :     Ouvre un fichier dans l'éditeur VIM"
}